### ISSUE TITLE
Redirection to Nike website

### ISSUE THREAD

**Issue by BuonOmo** [mickaelandrieu/choisirunelicence#10]
http://www.choisirunelicence.com now redirects to Nike website.

**Comment by mlinksva** [comment]
That's too bad. If the `CNAME` file is removed it should be available at https://mickaelandrieu.github.io/choisirunelicence/

**Comment by mickaelandrieu** [comment]
its mainly because I've abandonned the project and no one in the community was interested to maintain it. I encourage you to fork and host it :)

**Comment by mickaelandrieu** [comment]
I'll accept a pull request to remove CNAME file btw

**Comment by BuonOmo** [comment]
Done, though I don't know if github will publish automatically or if you have to do this in your settings

**Comment by mickaelandrieu** [comment]
This is ok now but the website is totally broken :/  I can't promise but I'll try to fix it asap.

Still, if you're interested on maintain it, you are very welcome :)

**Comment by BuonOmo** [comment]
Do you know the issues ? I'm not sure I'll have time to maintain it but I can help you for sure :)

**Comment by mickaelandrieu** [comment]
I really don't know :/ sorry!

**Comment by mlinksva** [comment]
Issues are due to use of absolute paths like:

```
    <link rel="stylesheet" href="/assets/vendor/normalize-css/normalize.css">
```

To make work at root or in subdirectory would need to change based on path or add full URL as variable.

**Comment by BuonOmo** [comment]
Maybe that would be solved by rebasing onto the original repo (I don't think github team would do this mistake..).

**Comment by mlinksva** [comment]
Nope, it's in the original repo. It just wasn't designed to work from a subdirectory. I'll see if I can fix that in the original site, but no promises as to how quickly. Pull requests welcome. :smile:

**Comment by thomaskuntzz** [comment]
I just opened a pull request for this #12
